steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nutrition-microservice', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nutrition-microservice']

images:
  - 'gcr.io/$PROJECT_ID/nutrition-microservice'

options:
  logging: CLOUD_LOGGING_ONLY
